// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlE4qjuCKLxLXRx2-rrQpeyAuOgvmwM3o',
    appId: '1:716960493744:web:0bdd8c6cd8d20754a38b75',
    messagingSenderId: '716960493744',
    projectId: 'openemr-app',
    authDomain: 'openemr-app.firebaseapp.com',
    storageBucket: 'openemr-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFWOdA_U9OUM1nPY-dh2IONgXAWK8Zzxc',
    appId: '1:716960493744:android:0ee479b884cb703ea38b75',
    messagingSenderId: '716960493744',
    projectId: 'openemr-app',
    storageBucket: 'openemr-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFBnFYHP-zJ0BrQKWUAvM6Q2qi-kyKres',
    appId: '1:716960493744:ios:be4d66e4f3819ceda38b75',
    messagingSenderId: '716960493744',
    projectId: 'openemr-app',
    storageBucket: 'openemr-app.appspot.com',
    iosBundleId: 'com.example.openemr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFBnFYHP-zJ0BrQKWUAvM6Q2qi-kyKres',
    appId: '1:716960493744:ios:8d3ec2e8a62b69a6a38b75',
    messagingSenderId: '716960493744',
    projectId: 'openemr-app',
    storageBucket: 'openemr-app.appspot.com',
    iosBundleId: 'com.example.openemr.RunnerTests',
  );
}
